[FEATURE] Implementação de novas funcionalidades de Sh3DataTableEditable
sh3-sistemas/Vexis3 pull request #1
Opened 2024-12-20 14:32 UTC by guilherme-batista-sh3

## Descrição

Aumento do contexto de `Sh3DataTableEditable`, de modo que seja possível usar um componente customizado para editar os dados da tabela e adição de `disabled` props
De acordo com [#117](https://github.com/sh3-sistemas/departamento-pessoal/issues/117)

### O que essa PR faz? 

Aumento do contexto de `Sh3DataTableEditable`

### Issue(s) Relacionada(s)

Resolve [#120](https://github.com/sh3-sistemas/departamento-pessoal/issues/120)

---
## Alterações
### Tipo de mudança
> Por favor, apague as opções que não são relevantes.

- [ ] Correção de bug (mudança que corrige um problema)
- [ ] Nova funcionalidade (mudança que adiciona uma nova funcionalidade)
- [ ] Atualização de documentação

### Checklist

- [ ] Meu código segue as diretrizes de estilo deste projeto.
- [ ] Eu realizei uma autoavaliação do meu próprio código.
- [ ] Comentei meu código, principalmente em áreas difíceis de entender.
- [ ] Fiz as alterações correspondentes na documentação.
- [ ] Minhas mudanças não geram novas _warnings_.
- [ ] Adicionei testes que provam que a correção é eficaz ou que a funcionalidade funciona.
- [ ] Testes novos e existentes passam localmente com minhas alterações.

### Capturas de Tela (se aplicável)
> Inclua capturas de tela, se relevante, para mostrar os resultados antes e depois das suas mudanças.

---
## Comentários Adicionais
> Adicione qualquer outro contexto ou informação aqui que possa ser útil para os revisores.

2025-01-02 13:22 UTC, barbara-b-boechat-sh3 requested changes

2025-01-02 13:22 UTC, barbara-b-boechat-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +};
Acredito que essa função pode ser uma variável computada

2025-01-02 13:22 UTC, barbara-b-boechat-sh3 commented on src/components/Tables/DataTable/types/index.ts
> +  cellFormaterEdit: { component: object; props: object; name?: string };
Adicione um comentário //TODO: para realizarmos a tipagem correta desses valores em breve

2025-01-02 19:36 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
>            v-model="row[field]"
Esse trecho em específico só será usado para edição de texto em linha, acredito que a edição de um atributo mais interno só será feita usando um componente customizado.

2025-01-02 19:39 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/types/index.ts
> +  cellFormaterEdit: { component: object; props: object; name?: string };
Resolvido

2025-01-02 19:39 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +};
Corrigido.

2025-01-06 17:48 UTC, barbara-b-boechat-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
>            v-model="row[field]"
hmm pode ser que sim, mas caso tenhamos algum problema com isso fica de aviso a possibilidade de utilizar esse método

2025-01-06 17:51 UTC, barbara-b-boechat-sh3 approved these changes

2025-01-06 17:51 UTC, merged